/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.opciones;

import Clases.producto.Producto;
import gui.opciones.*;
import gui.registroylogin.*;
import gui.principal.pantallas.*;
import java.awt.*;
import java.util.ArrayList;
import logica.Listas;

/**
 *
 * @author Arturo
 */
public class PantallaInicio extends javax.swing.JPanel {

    /**
     * Creates new form PantPrincipal
     */
    public PantallaInicio() {
        initComponents();
        textoSaludoCliente.setText("Hola, " + Listas.getUsuarioActual());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipalHUD = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        botonInicio = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        botonCarrito = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        botonMiInformacion = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        botonSalir = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        textoSaludoCliente = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        textoQueDeseas = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        botonFrutas = new javax.swing.JButton();
        botonCereales = new javax.swing.JButton();
        botonCarnes = new javax.swing.JButton();
        botonOtros = new javax.swing.JButton();
        botonAseo = new javax.swing.JButton();
        botonVerduras = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(350, 519));
        setMinimumSize(new java.awt.Dimension(350, 519));
        setPreferredSize(new java.awt.Dimension(350, 519));
        setLayout(new java.awt.BorderLayout());

        panelPrincipalHUD.setBackground(new java.awt.Color(254, 255, 234));
        panelPrincipalHUD.setPreferredSize(new java.awt.Dimension(350, 600));

        botonInicio.setText("Inicio");
        botonInicio.setPreferredSize(new java.awt.Dimension(65, 65));
        botonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioActionPerformed(evt);
            }
        });
        jPanel5.add(botonInicio);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setPreferredSize(new java.awt.Dimension(3, 50));
        jPanel5.add(jSeparator2);

        botonCarrito.setText("Carrito");
        botonCarrito.setPreferredSize(new java.awt.Dimension(65, 65));
        botonCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarritoActionPerformed(evt);
            }
        });
        jPanel5.add(botonCarrito);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(3, 50));
        jPanel5.add(jSeparator1);

        botonMiInformacion.setText("Mi info");
        botonMiInformacion.setPreferredSize(new java.awt.Dimension(65, 65));
        botonMiInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMiInformacionActionPerformed(evt);
            }
        });
        jPanel5.add(botonMiInformacion);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(3, 50));
        jPanel5.add(jSeparator3);

        botonSalir.setText("Salir");
        botonSalir.setPreferredSize(new java.awt.Dimension(65, 65));
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        jPanel5.add(botonSalir);

        panelPrincipal.setBackground(new java.awt.Color(51, 255, 51));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(350, 519));
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(204, 204, 0));

        textoSaludoCliente.setText("Hola,(Nombre)");
        jPanel1.add(textoSaludoCliente);

        textoQueDeseas.setText("¿Que deseas hoy?");
        jPanel7.add(textoQueDeseas);

        botonFrutas.setText("Frutas");
        botonFrutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFrutasActionPerformed(evt);
            }
        });

        botonCereales.setText("Cereales");
        botonCereales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerealesActionPerformed(evt);
            }
        });

        botonCarnes.setText("Carnes");
        botonCarnes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarnesActionPerformed(evt);
            }
        });

        botonOtros.setText("Otros");
        botonOtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOtrosActionPerformed(evt);
            }
        });

        botonAseo.setText("Aseo");
        botonAseo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAseoActionPerformed(evt);
            }
        });

        botonVerduras.setText("Verduras");
        botonVerduras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerdurasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(botonFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonVerduras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonCereales, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(botonCarnes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonAseo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVerduras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCereales, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAseo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarnes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        panelPrincipal.add(jPanel6, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panelPrincipalHUDLayout = new javax.swing.GroupLayout(panelPrincipalHUD);
        panelPrincipalHUD.setLayout(panelPrincipalHUDLayout);
        panelPrincipalHUDLayout.setHorizontalGroup(
            panelPrincipalHUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPrincipalHUDLayout.setVerticalGroup(
            panelPrincipalHUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalHUDLayout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(panelPrincipalHUD, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void botonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioActionPerformed
        // TODO add your handling code here:
        PantallaInicio p1 = new PantallaInicio();
        p1.setSize(350, 519);
        p1.setLocation(0, 0);

        panelPrincipal.removeAll();
        panelPrincipal.add(p1, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_botonInicioActionPerformed

    private void botonCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarritoActionPerformed
        // TODO add your handling code here:
        PantallaCarrito p2 = new PantallaCarrito();
        p2.setSize(350, 519);
        p2.setLocation(0, 0);

        panelPrincipal.removeAll();
        panelPrincipal.add(p2, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_botonCarritoActionPerformed

    private void botonMiInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMiInformacionActionPerformed
        // TODO add your handling code here:
        PantallaMiInformacion p3 = new PantallaMiInformacion();
        p3.setSize(350, 519);
        p3.setLocation(0, 0);

        panelPrincipal.removeAll();
        panelPrincipal.add(p3, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_botonMiInformacionActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        limpiarCarrito();
        
        PantallaLogin p4 = new PantallaLogin();
        p4.setSize(350, 600);
        p4.setLocation(0, 0);

        panelPrincipalHUD.removeAll();
        panelPrincipalHUD.add(p4, BorderLayout.CENTER);
        panelPrincipalHUD.revalidate();
        panelPrincipalHUD.repaint();
        
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonFrutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFrutasActionPerformed
        // TODO add your handling code here:
        PanelFrutas p5 = new PanelFrutas();
        p5.setSize(350, 519);
        p5.setLocation(0, 0);

        panelPrincipal.removeAll();
        panelPrincipal.add(p5, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_botonFrutasActionPerformed

    private void botonCerealesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerealesActionPerformed
        // TODO add your handling code here:
        PanelCereales p6 = new PanelCereales();
        p6.setSize(350, 519);
        p6.setLocation(0, 0);

        panelPrincipal.removeAll();
        panelPrincipal.add(p6, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_botonCerealesActionPerformed

    private void botonCarnesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarnesActionPerformed
        // TODO add your handling code here:
        PanelCarnes p7 = new PanelCarnes();
        p7.setSize(350, 519);
        p7.setLocation(0, 0);

        panelPrincipal.removeAll();
        panelPrincipal.add(p7, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_botonCarnesActionPerformed

    private void botonOtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOtrosActionPerformed
        // TODO add your handling code here:
        PanelOtros p8 = new PanelOtros();
        p8.setSize(350, 519);
        p8.setLocation(0, 0);

        panelPrincipal.removeAll();
        panelPrincipal.add(p8, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_botonOtrosActionPerformed

    private void botonAseoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAseoActionPerformed
        // TODO add your handling code here:
        PanelAseo p9 = new PanelAseo();
        p9.setSize(350, 519);
        p9.setLocation(0, 0);

        panelPrincipal.removeAll();
        panelPrincipal.add(p9, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_botonAseoActionPerformed

    private void botonVerdurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerdurasActionPerformed
        // TODO add your handling code here:
        PanelVerduras p10 = new PanelVerduras();
        p10.setSize(350, 519);
        p10.setLocation(0, 0);

        panelPrincipal.removeAll();
        panelPrincipal.add(p10, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_botonVerdurasActionPerformed

    private void limpiarCarrito() {
        ArrayList<Producto> Cero = new ArrayList<>();
        Listas.setListaCarrito(Cero);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAseo;
    private javax.swing.JButton botonCarnes;
    private javax.swing.JButton botonCarrito;
    private javax.swing.JButton botonCereales;
    private javax.swing.JButton botonFrutas;
    private javax.swing.JButton botonInicio;
    private javax.swing.JButton botonMiInformacion;
    private javax.swing.JButton botonOtros;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonVerduras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelPrincipalHUD;
    private javax.swing.JLabel textoQueDeseas;
    private javax.swing.JLabel textoSaludoCliente;
    // End of variables declaration//GEN-END:variables
}
