package gui;

import Clases.producto.Producto;
import Clases.producto.tipos.*;
import gui.principal.pantallas.*;
import java.awt.BorderLayout;
import gui.registroylogin.*;
import java.util.ArrayList;
import logica.Listas;

public class Launcher extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalJform
     */
    public Launcher() {
        initComponents();
        Listas.setListaProductos(Listas.crearListaInicialProductos());
        iniciarListasProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        textoPrincipal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botonEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPrincipal.setBackground(new java.awt.Color(0, 0, 204));

        jPanel7.setBackground(new java.awt.Color(0, 204, 102));
        jPanel7.setMinimumSize(new java.awt.Dimension(350, 600));
        jPanel7.setPreferredSize(new java.awt.Dimension(350, 500));

        textoPrincipal.setText("Coop");
        jPanel1.add(textoPrincipal);

        botonEntrar.setText("Entrar");
        botonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntrarActionPerformed(evt);
            }
        });
        jPanel2.add(botonEntrar);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntrarActionPerformed
        // TODO add your handling code here:
        PantallaLogin p1 = new PantallaLogin();
        p1.setSize(350, 600);
        p1.setLocation(0, 0);

        panelPrincipal.removeAll();
        panelPrincipal.add(p1, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_botonEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Launcher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Launcher().setVisible(true);
            }
        });

        System.out.println("hola");

    }

    //Mio
    private void iniciarListasProductos() {

        ArrayList<Producto> listaLocal = new ArrayList<>();
        listaLocal = Listas.getListaProductos();

        ArrayList<Fruta> listaFrutasLocal = new ArrayList<>();
        ArrayList<Verdura> listaVerdurasLocal = new ArrayList<>();
        ArrayList<Cereal> listaCerealesLocal = new ArrayList<>();
        ArrayList<Carne> listaCarnesLocal = new ArrayList<>();
        ArrayList<Aseo> listaAseoLocal = new ArrayList<>();
        ArrayList<Otro> listaOtrosLocal = new ArrayList<>();

        for (int i = 0; i < listaLocal.size(); i++) {

            if (listaLocal.get(i) instanceof Fruta) {
                Fruta tmp = (Fruta) listaLocal.get(i);
                
                listaFrutasLocal.add(tmp);

            }else if(listaLocal.get(i) instanceof Verdura){
                Verdura tmp = (Verdura) listaLocal.get(i);
                
                listaVerdurasLocal.add(tmp);
                
            }else if(listaLocal.get(i) instanceof Cereal){
                Cereal tmp = (Cereal) listaLocal.get(i);
                
                listaCerealesLocal.add(tmp);
                
            }else if(listaLocal.get(i) instanceof Carne){
                Carne tmp = (Carne) listaLocal.get(i);
                
                listaCarnesLocal.add(tmp);
                
            }else if(listaLocal.get(i) instanceof Aseo){
                Aseo tmp = (Aseo) listaLocal.get(i);
                
                listaAseoLocal.add(tmp);
                
            }else if(listaLocal.get(i) instanceof Otro){
                Otro tmp = (Otro) listaLocal.get(i);
                
                listaOtrosLocal.add(tmp);
                
            }

        }
        PanelFrutas.setListaFrutas(listaFrutasLocal);
        PanelVerduras.setListaVerduras(listaVerdurasLocal);
        PanelCereales.setListaCereales(listaCerealesLocal);
        PanelCarnes.setListaCarnes(listaCarnesLocal);
        PanelAseo.setListaAseo(listaAseoLocal);
        PanelOtros.setListaOtros(listaOtrosLocal);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEntrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel textoPrincipal;
    // End of variables declaration//GEN-END:variables
}
