/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.principal.pantallas.producto;

import Clases.producto.Producto;
import Clases.producto.tipos.*;
import gui.opciones.PantallaInicio;
import gui.principal.pantallas.*;
import java.awt.BorderLayout;
import java.util.ArrayList;
import logica.Listas;

/**
 *
 * @author Arturo
 */
public class PantallaVerProducto extends javax.swing.JPanel {

    private static int index;

    public static int getIndex() {
        return index;
    }

    public static void setIndex(int aIndex) {
        index = aIndex;
    }

    /**
     * Creates new form PantallaVerProducto
     */
    public PantallaVerProducto() {
        initComponents();
        llenarDatos();

        System.out.println(index);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        textoPrincipal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botonVolverAtras = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        botonAgregarCarrito = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        textoItem = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        textoRespuesta1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        textoItem1 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        textoRespuesta2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        textoItem2 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        textoRespuesta3 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        textoItem3 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        textoRespuesta4 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        textoItem4 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        textoRespuesta5 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        textoItem5 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        textoRespuesta6 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        textoItem6 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        textoRespuesta7 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        textoItem7 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        textoRespuesta8 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        textoItem8 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        textoRespuesta9 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        textoItem9 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        textoRespuesta10 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(350, 519));
        setPreferredSize(new java.awt.Dimension(350, 519));

        panelPrincipal.setBackground(new java.awt.Color(225, 244, 203));
        panelPrincipal.setMinimumSize(new java.awt.Dimension(350, 519));

        jPanel2.setBackground(new java.awt.Color(241, 191, 152));
        jPanel2.setLayout(new java.awt.BorderLayout());

        textoPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        textoPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        textoPrincipal.setText("Producto");
        jPanel2.add(textoPrincipal, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setOpaque(false);

        botonVolverAtras.setText("<");
        botonVolverAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(botonVolverAtras);

        jPanel2.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(new java.awt.Color(225, 244, 203));

        jPanel3.setBackground(new java.awt.Color(241, 191, 152));

        botonAgregarCarrito.setText("Agregar al Carrito");
        botonAgregarCarrito.setPreferredSize(new java.awt.Dimension(150, 50));
        botonAgregarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarCarritoActionPerformed(evt);
            }
        });
        jPanel3.add(botonAgregarCarrito);

        jPanel5.setBackground(new java.awt.Color(186, 203, 169));

        jPanel9.setBackground(new java.awt.Color(102, 255, 153));
        jPanel9.setOpaque(false);

        jPanel6.setBackground(new java.awt.Color(204, 0, 153));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setOpaque(false);

        textoItem.setForeground(new java.awt.Color(0, 0, 0));
        textoItem.setText("1");
        jPanel7.add(textoItem);

        jPanel6.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(204, 255, 255));
        jPanel8.setOpaque(false);

        textoRespuesta1.setForeground(new java.awt.Color(0, 0, 0));
        textoRespuesta1.setText("2");
        jPanel8.add(textoRespuesta1);

        jPanel6.add(jPanel8);

        jPanel9.add(jPanel6);

        jPanel10.setBackground(new java.awt.Color(102, 255, 153));
        jPanel10.setOpaque(false);

        jPanel11.setBackground(new java.awt.Color(204, 0, 153));
        jPanel11.setOpaque(false);
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        jPanel12.setBackground(new java.awt.Color(204, 255, 255));
        jPanel12.setOpaque(false);

        textoItem1.setForeground(new java.awt.Color(0, 0, 0));
        textoItem1.setText("1");
        jPanel12.add(textoItem1);

        jPanel11.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(204, 255, 255));
        jPanel13.setOpaque(false);

        textoRespuesta2.setForeground(new java.awt.Color(0, 0, 0));
        textoRespuesta2.setText("2");
        jPanel13.add(textoRespuesta2);

        jPanel11.add(jPanel13);

        jPanel10.add(jPanel11);

        jPanel14.setBackground(new java.awt.Color(102, 255, 153));
        jPanel14.setOpaque(false);

        jPanel15.setBackground(new java.awt.Color(204, 0, 153));
        jPanel15.setOpaque(false);
        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.LINE_AXIS));

        jPanel16.setBackground(new java.awt.Color(204, 255, 255));
        jPanel16.setOpaque(false);

        textoItem2.setForeground(new java.awt.Color(0, 0, 0));
        textoItem2.setText("1");
        jPanel16.add(textoItem2);

        jPanel15.add(jPanel16);

        jPanel17.setBackground(new java.awt.Color(204, 255, 255));
        jPanel17.setOpaque(false);

        textoRespuesta3.setForeground(new java.awt.Color(0, 0, 0));
        textoRespuesta3.setText("2");
        jPanel17.add(textoRespuesta3);

        jPanel15.add(jPanel17);

        jPanel14.add(jPanel15);

        jPanel18.setBackground(new java.awt.Color(102, 255, 153));
        jPanel18.setOpaque(false);

        jPanel19.setBackground(new java.awt.Color(204, 0, 153));
        jPanel19.setOpaque(false);
        jPanel19.setLayout(new javax.swing.BoxLayout(jPanel19, javax.swing.BoxLayout.LINE_AXIS));

        jPanel20.setBackground(new java.awt.Color(204, 255, 255));
        jPanel20.setOpaque(false);

        textoItem3.setForeground(new java.awt.Color(0, 0, 0));
        textoItem3.setText("1");
        jPanel20.add(textoItem3);

        jPanel19.add(jPanel20);

        jPanel21.setBackground(new java.awt.Color(204, 255, 255));
        jPanel21.setOpaque(false);

        textoRespuesta4.setForeground(new java.awt.Color(0, 0, 0));
        textoRespuesta4.setText("2");
        jPanel21.add(textoRespuesta4);

        jPanel19.add(jPanel21);

        jPanel18.add(jPanel19);

        jPanel22.setBackground(new java.awt.Color(102, 255, 153));
        jPanel22.setOpaque(false);

        jPanel23.setBackground(new java.awt.Color(204, 0, 153));
        jPanel23.setOpaque(false);
        jPanel23.setLayout(new javax.swing.BoxLayout(jPanel23, javax.swing.BoxLayout.LINE_AXIS));

        jPanel24.setBackground(new java.awt.Color(204, 255, 255));
        jPanel24.setOpaque(false);

        textoItem4.setForeground(new java.awt.Color(0, 0, 0));
        textoItem4.setText("1");
        jPanel24.add(textoItem4);

        jPanel23.add(jPanel24);

        jPanel25.setBackground(new java.awt.Color(204, 255, 255));
        jPanel25.setOpaque(false);

        textoRespuesta5.setForeground(new java.awt.Color(0, 0, 0));
        textoRespuesta5.setText("2");
        jPanel25.add(textoRespuesta5);

        jPanel23.add(jPanel25);

        jPanel22.add(jPanel23);

        jPanel26.setBackground(new java.awt.Color(102, 255, 153));
        jPanel26.setOpaque(false);

        jPanel27.setBackground(new java.awt.Color(204, 0, 153));
        jPanel27.setOpaque(false);
        jPanel27.setLayout(new javax.swing.BoxLayout(jPanel27, javax.swing.BoxLayout.LINE_AXIS));

        jPanel28.setBackground(new java.awt.Color(204, 255, 255));
        jPanel28.setOpaque(false);

        textoItem5.setForeground(new java.awt.Color(0, 0, 0));
        textoItem5.setText("1");
        jPanel28.add(textoItem5);

        jPanel27.add(jPanel28);

        jPanel29.setBackground(new java.awt.Color(204, 255, 255));
        jPanel29.setOpaque(false);

        textoRespuesta6.setForeground(new java.awt.Color(0, 0, 0));
        textoRespuesta6.setText("2");
        jPanel29.add(textoRespuesta6);

        jPanel27.add(jPanel29);

        jPanel26.add(jPanel27);

        jPanel30.setBackground(new java.awt.Color(102, 255, 153));
        jPanel30.setOpaque(false);

        jPanel31.setBackground(new java.awt.Color(204, 0, 153));
        jPanel31.setOpaque(false);
        jPanel31.setLayout(new javax.swing.BoxLayout(jPanel31, javax.swing.BoxLayout.LINE_AXIS));

        jPanel32.setBackground(new java.awt.Color(204, 255, 255));
        jPanel32.setOpaque(false);

        textoItem6.setForeground(new java.awt.Color(0, 0, 0));
        textoItem6.setText("1");
        jPanel32.add(textoItem6);

        jPanel31.add(jPanel32);

        jPanel33.setBackground(new java.awt.Color(204, 255, 255));
        jPanel33.setOpaque(false);

        textoRespuesta7.setForeground(new java.awt.Color(0, 0, 0));
        textoRespuesta7.setText("2");
        jPanel33.add(textoRespuesta7);

        jPanel31.add(jPanel33);

        jPanel30.add(jPanel31);

        jPanel34.setBackground(new java.awt.Color(102, 255, 153));
        jPanel34.setOpaque(false);

        jPanel35.setBackground(new java.awt.Color(204, 0, 153));
        jPanel35.setOpaque(false);
        jPanel35.setLayout(new javax.swing.BoxLayout(jPanel35, javax.swing.BoxLayout.LINE_AXIS));

        jPanel36.setBackground(new java.awt.Color(204, 255, 255));
        jPanel36.setOpaque(false);

        textoItem7.setForeground(new java.awt.Color(0, 0, 0));
        textoItem7.setText("1");
        jPanel36.add(textoItem7);

        jPanel35.add(jPanel36);

        jPanel37.setBackground(new java.awt.Color(204, 255, 255));
        jPanel37.setOpaque(false);

        textoRespuesta8.setForeground(new java.awt.Color(0, 0, 0));
        textoRespuesta8.setText("2");
        jPanel37.add(textoRespuesta8);

        jPanel35.add(jPanel37);

        jPanel34.add(jPanel35);

        jPanel38.setBackground(new java.awt.Color(102, 255, 153));
        jPanel38.setOpaque(false);

        jPanel39.setBackground(new java.awt.Color(204, 0, 153));
        jPanel39.setOpaque(false);
        jPanel39.setLayout(new javax.swing.BoxLayout(jPanel39, javax.swing.BoxLayout.LINE_AXIS));

        jPanel40.setBackground(new java.awt.Color(204, 255, 255));
        jPanel40.setOpaque(false);

        textoItem8.setForeground(new java.awt.Color(0, 0, 0));
        textoItem8.setText("1");
        jPanel40.add(textoItem8);

        jPanel39.add(jPanel40);

        jPanel41.setBackground(new java.awt.Color(204, 255, 255));
        jPanel41.setOpaque(false);

        textoRespuesta9.setForeground(new java.awt.Color(0, 0, 0));
        textoRespuesta9.setText("2");
        jPanel41.add(textoRespuesta9);

        jPanel39.add(jPanel41);

        jPanel38.add(jPanel39);

        jPanel42.setBackground(new java.awt.Color(102, 255, 153));
        jPanel42.setOpaque(false);

        jPanel43.setBackground(new java.awt.Color(204, 0, 153));
        jPanel43.setOpaque(false);
        jPanel43.setLayout(new javax.swing.BoxLayout(jPanel43, javax.swing.BoxLayout.LINE_AXIS));

        jPanel44.setBackground(new java.awt.Color(204, 255, 255));
        jPanel44.setOpaque(false);

        textoItem9.setForeground(new java.awt.Color(0, 0, 0));
        textoItem9.setText("1");
        jPanel44.add(textoItem9);

        jPanel43.add(jPanel44);

        jPanel45.setBackground(new java.awt.Color(204, 255, 255));
        jPanel45.setOpaque(false);

        textoRespuesta10.setForeground(new java.awt.Color(0, 0, 0));
        textoRespuesta10.setText("2");
        jPanel45.add(textoRespuesta10);

        jPanel43.add(jPanel45);

        jPanel42.add(jPanel43);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel42, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverAtrasActionPerformed
        // TODO add your handling code here:
        irPantallaAnterior();
    }//GEN-LAST:event_botonVolverAtrasActionPerformed

    private void botonAgregarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarCarritoActionPerformed
        // TODO add your handling code here:
        agregarAlCarrito();
        irPantallaPrincipal();
    }//GEN-LAST:event_botonAgregarCarritoActionPerformed

    private void llenarDatos() {
        ArrayList<Producto> listaLocal = new ArrayList<>();
        listaLocal = Listas.getListaProductos();

        textoPrincipal.setText(listaLocal.get(index).getNombre());

        if (listaLocal.get(index) instanceof Fruta) {
            Fruta tmp = (Fruta) listaLocal.get(index);

            textoItem.setText("Nombre: ");
            textoRespuesta1.setText(tmp.getNombre());

            textoItem1.setText("Descripcion: ");
            textoRespuesta2.setText(tmp.getDescripcion());

            textoItem2.setText("Id: ");
            textoRespuesta3.setText(String.valueOf(tmp.getId()));

            textoItem3.setText("Tipo: ");
            textoRespuesta4.setText(tmp.getTipo());

            textoItem4.setText("Precio: ");
            textoRespuesta5.setText("$ " + String.valueOf(tmp.getPrecio()));

            textoItem5.setText("Importado: ");
            textoItem6.setText("Pais de Impor: ");
            if (tmp.isProductoImportado() == false) {
                textoRespuesta6.setText("No");
                textoRespuesta7.setText("No aplica");
            } else {
                textoRespuesta6.setText("Si");
                textoRespuesta7.setText(tmp.getPaisdeImportacion());
            }

            textoItem7.setText("Organico: ");
            if (tmp.isTotalmenteOrganico() == false) {
                textoRespuesta8.setText("No");

            } else {
                textoRespuesta8.setText("Si");
            }

            textoItem8.setText("Peso: ");
            textoRespuesta9.setText(String.valueOf(tmp.getPeso()) + "gr");

            textoItem9.setText("Especie: ");
            textoRespuesta10.setText(tmp.getEspecie());

        } else if (listaLocal.get(index) instanceof Verdura) {
            Verdura tmp = (Verdura) listaLocal.get(index);

            textoItem.setText("Nombre: ");
            textoRespuesta1.setText(tmp.getNombre());

            textoItem1.setText("Descripcion: ");
            textoRespuesta2.setText(tmp.getDescripcion());

            textoItem2.setText("Id: ");
            textoRespuesta3.setText(String.valueOf(tmp.getId()));

            textoItem3.setText("Tipo: ");
            textoRespuesta4.setText(tmp.getTipo());

            textoItem4.setText("Precio: ");
            textoRespuesta5.setText("$ " + String.valueOf(tmp.getPrecio()));

            textoItem5.setText("Importado: ");
            textoItem6.setText("Pais de Impor: ");
            if (tmp.isProductoImportado() == false) {
                textoRespuesta6.setText("No");
                textoRespuesta7.setText("No aplica");
            } else {
                textoRespuesta6.setText("Si");
                textoRespuesta7.setText(tmp.getPaisdeImportacion());
            }

            textoItem7.setText("Organico: ");
            if (tmp.isTotalmenteOrganico() == false) {
                textoRespuesta8.setText("No");

            } else {
                textoRespuesta8.setText("Si");
            }

            textoItem8.setText("Peso: ");
            textoRespuesta9.setText(String.valueOf(tmp.getPeso()) + "gr");

            textoItem9.setText("Especie: ");
            textoRespuesta10.setText(tmp.getEspecie());

        } else if (listaLocal.get(index) instanceof Cereal) {
            Cereal tmp = (Cereal) listaLocal.get(index);

            textoItem.setText("Nombre: ");
            textoRespuesta1.setText(tmp.getNombre());

            textoItem1.setText("Descripcion: ");
            textoRespuesta2.setText(tmp.getDescripcion());

            textoItem2.setText("Id: ");
            textoRespuesta3.setText(String.valueOf(tmp.getId()));

            textoItem3.setText("Tipo: ");
            textoRespuesta4.setText(tmp.getTipo());

            textoItem4.setText("Precio: ");
            textoRespuesta5.setText("$ " + String.valueOf(tmp.getPrecio()));

            textoItem5.setText("Importado: ");
            textoItem6.setText("Pais de Impor: ");
            if (tmp.isProductoImportado() == false) {
                textoRespuesta6.setText("No");
                textoRespuesta7.setText("No aplica");
            } else {
                textoRespuesta6.setText("Si");
                textoRespuesta7.setText(tmp.getPaisdeImportacion());
            }

            textoItem7.setText("Gluten: ");
            if (tmp.isTieneGluten() == false) {
                textoRespuesta8.setText("No");

            } else {
                textoRespuesta8.setText("Si");
            }

            textoItem8.setText("Peso: ");
            textoRespuesta9.setText(String.valueOf(tmp.getPeso()) + "gr");

            textoItem9.setText("Especie: ");
            textoRespuesta10.setText(tmp.getEspecie());

        } else if (listaLocal.get(index) instanceof Carne) {
            Carne tmp = (Carne) listaLocal.get(index);

            textoItem.setText("Nombre: ");
            textoRespuesta1.setText(tmp.getNombre());

            textoItem1.setText("Descripcion: ");
            textoRespuesta2.setText(tmp.getDescripcion());

            textoItem2.setText("Id: ");
            textoRespuesta3.setText(String.valueOf(tmp.getId()));

            textoItem3.setText("Tipo: ");
            textoRespuesta4.setText(tmp.getTipo());

            textoItem4.setText("Precio: ");
            textoRespuesta5.setText("$ " + String.valueOf(tmp.getPrecio()));

            textoItem5.setText("Importado: ");
            textoItem6.setText("Pais de Impor: ");
            if (tmp.isProductoImportado() == false) {
                textoRespuesta6.setText("No");
                textoRespuesta7.setText("No aplica");
            } else {
                textoRespuesta6.setText("Si");
                textoRespuesta7.setText(tmp.getPaisdeImportacion());
            }

            textoItem7.setText("Procesado: ");
            if (tmp.isProcesado() == false) {
                textoRespuesta8.setText("No");

            } else {
                textoRespuesta8.setText("Si");
            }

            textoItem8.setText("Peso: ");
            textoRespuesta9.setText(String.valueOf(tmp.getPeso()) + "gr");

            textoItem9.setText("Procedencia: ");
            textoRespuesta10.setText(tmp.getProcedencia());

        } else if (listaLocal.get(index) instanceof Aseo) {
            Aseo tmp = (Aseo) listaLocal.get(index);

            textoItem.setText("Nombre: ");
            textoRespuesta1.setText(tmp.getNombre());

            textoItem1.setText("Descripcion: ");
            textoRespuesta2.setText(tmp.getDescripcion());

            textoItem2.setText("Id: ");
            textoRespuesta3.setText(String.valueOf(tmp.getId()));

            textoItem3.setText("Tipo: ");
            textoRespuesta4.setText(tmp.getTipo());

            textoItem4.setText("Precio: ");
            textoRespuesta5.setText("$ " + String.valueOf(tmp.getPrecio()));

            textoItem5.setText("Importado: ");
            textoItem6.setText("Pais de Impor: ");
            if (tmp.isProductoImportado() == false) {
                textoRespuesta6.setText("No");
                textoRespuesta7.setText("No aplica");
            } else {
                textoRespuesta6.setText("Si");
                textoRespuesta7.setText(tmp.getPaisdeImportacion());
            }

            textoItem7.setText("Aseo Personal: ");
            if (tmp.isEsAseoPersonal() == false) {
                textoRespuesta8.setText("No");

            } else {
                textoRespuesta8.setText("Si");
            }

            textoItem8.setText("Peso: ");
            textoRespuesta9.setText(String.valueOf(tmp.getPeso()) + "gr");

            textoItem9.setText("Marca: ");
            textoRespuesta10.setText(tmp.getMarca());

        } else if (listaLocal.get(index) instanceof Otro) {
            Otro tmp = (Otro) listaLocal.get(index);

            textoItem.setText("Nombre: ");
            textoRespuesta1.setText(tmp.getNombre());

            textoItem1.setText("Descripcion: ");
            textoRespuesta2.setText(tmp.getDescripcion());

            textoItem2.setText("Id: ");
            textoRespuesta3.setText(String.valueOf(tmp.getId()));

            textoItem3.setText("Tipo: ");
            textoRespuesta4.setText(tmp.getTipo());

            textoItem4.setText("Precio: ");
            textoRespuesta5.setText("$ " + String.valueOf(tmp.getPrecio()));

            textoItem5.setText("Importado: ");
            textoItem6.setText("Pais de Impor: ");
            if (tmp.isProductoImportado() == false) {
                textoRespuesta6.setText("No");
                textoRespuesta7.setText("No aplica");
            } else {
                textoRespuesta6.setText("Si");
                textoRespuesta7.setText(tmp.getPaisdeImportacion());
            }

            textoItem7.setText("Comestible: ");
            if (tmp.isComestible() == false) {
                textoRespuesta8.setText("No");

            } else {
                textoRespuesta8.setText("Si");
            }

            textoItem8.setText("Artesania: ");
            if (tmp.isArtesania() == false) {
                textoRespuesta9.setText("No");

            } else {
                textoRespuesta9.setText("Si");
            }

            textoItem9.setText("Cantidad disponible: ");
            textoRespuesta10.setText(String.valueOf(tmp.getCantidadDisponible()));

        }
    }

    private void agregarAlCarrito() {
        ArrayList<Producto> listaSubir = new ArrayList<>();
        listaSubir = Listas.getListaCarrito();

        listaSubir.add(Listas.getListaProductos().get(index));

        Listas.setListaCarrito(listaSubir);
    }

    private void irPantallaPrincipal() {

        PantallaInicio p1 = new PantallaInicio();
        p1.setSize(350, 519);
        p1.setLocation(0, 0);

        panelPrincipal.removeAll();
        panelPrincipal.add(p1, BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();

    }

    private void irPantallaAnterior() {

        switch (Listas.getListaProductos().get(index).getTipo()) {

            case "Fruta":
                PanelFrutas p1 = new PanelFrutas();
                p1.setSize(350, 519);
                p1.setLocation(0, 0);

                panelPrincipal.removeAll();
                panelPrincipal.add(p1, BorderLayout.CENTER);
                panelPrincipal.revalidate();
                panelPrincipal.repaint();

                break;

            case "Verdura":
                PanelVerduras p2 = new PanelVerduras();
                p2.setSize(350, 519);
                p2.setLocation(0, 0);

                panelPrincipal.removeAll();
                panelPrincipal.add(p2, BorderLayout.CENTER);
                panelPrincipal.revalidate();
                panelPrincipal.repaint();

                break;

            case "Cereal":
                PanelCereales p3 = new PanelCereales();
                p3.setSize(350, 519);
                p3.setLocation(0, 0);

                panelPrincipal.removeAll();
                panelPrincipal.add(p3, BorderLayout.CENTER);
                panelPrincipal.revalidate();
                panelPrincipal.repaint();

                break;

            case "Carne":
                PanelCarnes p4 = new PanelCarnes();
                p4.setSize(350, 519);
                p4.setLocation(0, 0);

                panelPrincipal.removeAll();
                panelPrincipal.add(p4, BorderLayout.CENTER);
                panelPrincipal.revalidate();
                panelPrincipal.repaint();

                break;

            case "Aseo":
                PanelAseo p5 = new PanelAseo();
                p5.setSize(350, 519);
                p5.setLocation(0, 0);

                panelPrincipal.removeAll();
                panelPrincipal.add(p5, BorderLayout.CENTER);
                panelPrincipal.revalidate();
                panelPrincipal.repaint();

                break;

            case "Otro":
                PanelOtros p6 = new PanelOtros();
                p6.setSize(350, 519);
                p6.setLocation(0, 0);

                panelPrincipal.removeAll();
                panelPrincipal.add(p6, BorderLayout.CENTER);
                panelPrincipal.revalidate();
                panelPrincipal.repaint();

                break;

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarCarrito;
    private javax.swing.JButton botonVolverAtras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel textoItem;
    private javax.swing.JLabel textoItem1;
    private javax.swing.JLabel textoItem2;
    private javax.swing.JLabel textoItem3;
    private javax.swing.JLabel textoItem4;
    private javax.swing.JLabel textoItem5;
    private javax.swing.JLabel textoItem6;
    private javax.swing.JLabel textoItem7;
    private javax.swing.JLabel textoItem8;
    private javax.swing.JLabel textoItem9;
    private javax.swing.JLabel textoPrincipal;
    private javax.swing.JLabel textoRespuesta1;
    private javax.swing.JLabel textoRespuesta10;
    private javax.swing.JLabel textoRespuesta2;
    private javax.swing.JLabel textoRespuesta3;
    private javax.swing.JLabel textoRespuesta4;
    private javax.swing.JLabel textoRespuesta5;
    private javax.swing.JLabel textoRespuesta6;
    private javax.swing.JLabel textoRespuesta7;
    private javax.swing.JLabel textoRespuesta8;
    private javax.swing.JLabel textoRespuesta9;
    // End of variables declaration//GEN-END:variables
}
